INSERT INTO categories VALUES(0,"-- VEHICULES --", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Voitures", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Motos", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Caravaning", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Utilitaires", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Equipement Auto", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Equipement Moto", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Equipement Caravaning", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Nautisme", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Equipement Nautisme", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"-- MULTIMEDIA --", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Informatique", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Consoles & Jeux vidéo", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Image & Son", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Téléphonie", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"-- MAISON --", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Ameublement", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Electroménager", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Arts de la table", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Décoration", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Linge de maison", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Bricolage", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Jardinage", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Vêtements", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Chaussures", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Accessoires & Bagagerie", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Montres & Bijoux", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Equipement bébé", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Vêtements bébé", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"-- LOISIRS --", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"DVD / Films", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"CD / Musique", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Livres", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Animaux", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Vélos", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Sports & Hobbies", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Instruments de musique", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Collection", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Jeux & Jouets", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Vins & Gastronomie", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"-- MATERIEL PROFESSIONNEL --", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Matériel Agricole", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Transport - Manutention", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"BTP - Chantier Gros-oeuvre", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Outillage - Matériaux 2nd-oeuvre", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Équipements Industriels", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Restauration - Hôtellerie", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Fournitures de Bureau", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Commerces & Marchés", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Matériel Médical", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"--", CURDATE(), CURDATE());
INSERT INTO categories VALUES(0,"Autres", CURDATE(), CURDATE());